### ISSUE TITLE
Pages are missing header image

### ISSUE THREAD

**Issue by dcanones** [zutrinken/attila#101]
Hi,
It looks like Pages (as opposed to Posts) are missing the header image.

**Comment by matheusvanzan** [comment]
@dcanones I recently noticed it as well. You should replace `cover_image` by `feature_image`. 
I tested on a fresh clone of the repo and it worked.

**Comment by dcanones** [comment]
Thanks! Opened a pull request to fix this...

**Comment by zutrinken** [comment]
Fixed in #104
