### ISSUE TITLE
Toggle for Dark Mode

### ISSUE THREAD

**Issue by kayg04** [zutrinken/attila#105]
Would it be possible to add a toggle on the top right side of the page so that the visitor is able to choose between light and dark modes?

This feature should not change the automatic detection that is currently in place.

**Comment by Dorson** [comment]
Yes it is possible. The web apps and websites move into that direction.

Recently, I coded the Dark Mode switch in CSS and basic Java Script.

In my version of the dark mode, we can have multiple color themes in one CSS file. Then set or remember color settings with one short JS function without logins.

**Try it** on the GitHub demo page :

https://dorson.github.io/CSS-Dark-Mode-and-color-switch/

Feel free to fork, copy, adopt, etc..

Have fun ! :+1:

**Comment by jeff-ridgeway** [comment]
Is there some javascript code we can put in the header and footer for the toggle option? I would like this feature as well and it not be automatic but allow the user to choose.

**Comment by zutrinken** [comment]
[2.6.0](https://github.com/zutrinken/attila/releases/tag/2.6.0) includes theme switch. Located in footer.
