### ISSUE TITLE
Making changes to CSS and SCSS

### ISSUE THREAD

**Issue by vitolaterza** [zutrinken/attila#106]
Dear Attila team,

first of all well done on a slick and minimalist theme, we are using the theme for a new blog project and is working very well for our audience and goals.

I am a bit of a beginner with advanced coding, so I wanted to ask one question, if you have some guidance. I have started to make small changes to the theme by editing the CSS style file. I am now seeing that there are also SCSS files, including a style one. Do I need to make changes there too and standardise with the CSS changes? Or? So far, all changes I have done on the CSS work fine, but I haven't touched the SCSS files.

Thank you in advance for any advice you might be able to provide,

Vito

**Comment by tobimori** [comment]
Make changes to the scss file and then compile the css files with Grunt as described [here](https://github.com/zutrinken/attila#development).
