### ISSUE TITLE
Enable instant search

### ISSUE THREAD

**Issue by kayg04** [zutrinken/attila#107]
As far as the ghostHunter docs go, `onKeyUp` needs to be set to `true` for instant-search (search-as-you-type) to be enabled. However, upon enabling it in `src/js/script.js`, reloading the theme and restarting Ghost, there seems to be no effect at all?

Is attila using a modified version of ghostHunter? How would I go about achieving the same in attila?

**Comment by zutrinken** [comment]
🤷‍♂️ using default ghostHunter, but I'm actually not really happy with it in general. Would consider to switch to [ghost-search](https://github.com/HauntedThemes/ghost-search) or Ghost finally implements a search into the core.

I'm quite helpless with GhostHunter. If you manage to improve it I'm happy to see a PR.
