### ISSUE TITLE
A page for browsing tags

### ISSUE THREAD

**Issue by kayg04** [zutrinken/attila#108]
Currently, tags can only be seen through a post. It would be helpful if a separate section / category could be created for displaying tags. 

This feature can be marked as optional to maintain the minimal-by-default look of the theme.

**Comment by zutrinken** [comment]
Do you have an example from other themes?

**Comment by zutrinken** [comment]
@kayg04 when you activate the search there's also a tag list. Looks like this:

<img width="842" alt="Screenshot 2020-07-01 at 21 51 16" src="https://user-images.githubusercontent.com/888679/86285548-17d59680-bbe5-11ea-9e88-6d5442810370.png">
