### ISSUE TITLE
How do i view the website after running the grunt command? 

### ISSUE THREAD

**Issue by LearnedVector** [zutrinken/attila#111]
Trying to modify the theme. I come from the react world, using `yarn` so I have no idea how to run the app using grunt. Followed instructions to install grunt, build, then ran using grunt. but it just says `watching` without specifying how to open the app.

**Comment by zutrinken** [comment]
Grunt ist only used for building the theme. You have to install and run Ghost locally separately.

**Comment by kapookchang** [comment]
I using ghost install local and install a theme. Then open directory location theme and run "grunt default" for watching scss. Good luck.
