### ISSUE TITLE
2.0.3 two small strings not translated

### ISSUE THREAD

**Issue by cdorin93** [zutrinken/attila#115]
Hello everyone!

First, thank you for the awesome theme and update! I totally enjoy it :).
Secondly, I saw that some translation related issues have been fixed with the last updated. Wanted to ask if these were also fixed (see screenshot; on homepage, "in" and "on" are not translated). It seems that the json file contains the translations.

Best,
Dorin
![Screenshot from 2020-05-06 19-35-49](https://user-images.githubusercontent.com/28493662/81209520-2ece8280-8fc0-11ea-9e14-d5ee104fea0a.png)

**Comment by zutrinken** [comment]
Hey Dorin, Thanks. Means a lot :-)

You have to restart Ghost as well after updating the theme.

**Comment by cdorin93** [comment]
Silly me, yes, you are right. Thanks for your quick reply - it can be closed :)
