### ISSUE TITLE
Running Windows 10 in Dark Mode renders code blocks un-readable

### ISSUE THREAD

**Issue by mgmccarthy** [zutrinken/attila#116]
Running Windows 10 in Dark Mode
![image](https://user-images.githubusercontent.com/2428993/81808247-6f149000-94ed-11ea-9f32-21a1c511a1bc.png)

renders code blocks unreadable:
![image](https://user-images.githubusercontent.com/2428993/81808427-aedb7780-94ed-11ea-83f9-036771ffd04d.png)

I'm using Prism 1.20.0.

Running Windows in Light mode or Custom mode with "default Windows mode" set to Dark and "default app mode" set to Light
![image](https://user-images.githubusercontent.com/2428993/81808545-da5e6200-94ed-11ea-9182-5e81de964399.png)

Renders the code correctly
![image](https://user-images.githubusercontent.com/2428993/81808670-0e398780-94ee-11ea-9985-0b41e60145f1.png)

**Comment by zutrinken** [comment]
Thanks for the issue. It's fixed on master. Let me know if something is still odd.
