### ISSUE TITLE
Dark mode code block is unreadable

### ISSUE THREAD

**Issue by var-kar** [zutrinken/attila#117]
Dark mode code block is unreadable. Can we have a better theme for preformatted code blocks?
This is how it looks on my blog.

notice how function and return are so very dark.

<img width="788" alt="Screenshot 2020-05-14 at 02 09 33" src="https://user-images.githubusercontent.com/26141562/81863026-337ad400-9588-11ea-9ac7-7fe05c8a274d.png">

**Comment by zutrinken** [comment]
Thanks for the issue. It's fixed on master. Let me know if something is still odd.

**Comment by var-kar** [comment]
Thank you for fixing it :)
