### ISSUE TITLE
Subscribe by email

### ISSUE THREAD

**Issue by ilithium** [zutrinken/attila#118]
Hi there

Thanks for making this great theme!

Is there a way to make this work with Ghost 3.x so that users can subscribe to email updates?

I'd be happy to create a PR if I could get a few pointers.

Cheers!

**Comment by brettcannon** [comment]
I'll mention that this is the only thing stopping me from switching off of Casper for this theme. 😃

**Comment by zutrinken** [comment]
There's a branch for member feature. It's untested and could need some feedback.

https://github.com/zutrinken/attila/tree/members

**Comment by sp4rc** [comment]
Hi there, what's the status of the members tree/feature? Would love to see this in the master 😎
