### ISSUE TITLE
Font is very difficult to read

### ISSUE THREAD

**Issue by Jookia** [zutrinken/attila#121]
The font used in the theme is very difficult to read:

- Navigation and date text is much too small
- The kerning on the font is awful
- When the font is italic it hurts to read
- Some text is very low contrast

Screenshots:

![trouble1](https://user-images.githubusercontent.com/185275/83322659-1f51fa80-a249-11ea-9c5d-ce537c425a54.png)
![trouble2](https://user-images.githubusercontent.com/185275/83322693-532d2000-a249-11ea-971d-8b0e4f494b18.png)

**Comment by MarcoZehe** [comment]
@zutrinken This is in direct response to my blog relaunch. Anything we can do? Since this is visual stuff, I cannot actually fix it myself, because I wouldn‘t know what I was doing.

**Comment by rkingett** [comment]
Chiming in here, WAVE flags many contrast errors. I'm totally blind as well, so can't comment on this much, but I hope this can be fixed so that default adoption is possible.

**Comment by zutrinken** [comment]
I'll have a look into it.

**Comment by vimalkvn** [comment]
Looking for alternative fonts, I ended up using the following combination for my website and I am happy with the result:

**Merriweather** (serif)
**Lato** (sans-serif)
**Inconsolata** (monospace)

Here is a screenshot of a page using these fonts (1):

![organising-content](https://user-images.githubusercontent.com/239451/84566992-7b4e7000-ad6d-11ea-802c-4b803429def8.png)

Other font combinations can be found on Beautiful Web Type (2).

Please note, I haven't done any tests on accessibility on my website yet.

(1): https://vimaltech.com/organising-content
(2): https://beautifulwebtype.com/

**Comment by veteran1** [comment]
Any news on this issue? the font is still harsh and doesn't look smooth

**Comment by zutrinken** [comment]
@veteran1 Colors got adjusted, font-sizes got increased and it's now quite easy to change font via code injection. That's quite some news ...

I'll check out some other fonts at some point.

**Comment by veteran1** [comment]
Thanks for your reply, I will try to adjust the font via code injection.
the theme looks awesome by the way :)
