### ISSUE TITLE
What are jquery.history.js and nprogress.js used for?

### ISSUE THREAD

**Issue by AlexLomm** [zutrinken/attila#124]
First of all, thank you for sharing this incredible theme!

I discovered that the theme is using [jquery.history.js](https://github.com/zutrinken/attila/blob/master/src/js/libs/jquery.history.js) and [nprogress.js](https://github.com/zutrinken/attila/blob/master/src/js/libs/nprogress.js) libs. My question is, what are these libs used for and can they be safely removed?

Thank you

**Comment by zutrinken** [comment]
Good question. `nprogress.js` is used for reading progress for posts. Progress bar at window top.

`history.js` is for Ajax stuff. Used it in a previous theme and forgot to remove. So thanks for the hint.

**Comment by AlexLomm** [comment]
Sure thing. Btw, the `nprogress` is also not needed, because it seems like the reading progress is dealt with custom code.

**Comment by zutrinken** [comment]
oh boy, you're right. I forgot I rebuilt that thing in the end. So again, thanks for the hint :-)

**Comment by AlexLomm** [comment]
Np, keep up the good work :)
