### ISSUE TITLE
title, long text, cutoff

### ISSUE THREAD

**Issue by k3s4** [zutrinken/attila#125]
There is a problem with responsiveness when title is too long - there is cutoff (mobile)

Example:
![Screenshot_20200626-113436_Chrome](https://user-images.githubusercontent.com/13254565/85845164-231f6100-b7a4-11ea-892c-29eeee049600.jpg)

you can check how it should look like here - https://blog.sienicki.eu

**Comment by zutrinken** [comment]
The length is pretty individual and not so easy to make it dynamic. So I close this issue. I suggest changing it via code injection. This should do the job: 

```HTML
<style>
@media only screen and (max-width: 640px) {
	.blog-name {
		font-size: 4em;
	}
}
</style>
```
