### ISSUE TITLE
Changing theme colors via color injection?

### ISSUE THREAD

**Issue by vn78dev** [zutrinken/attila#126]
Can I somehow set $color-primary and other colors in the code injection? 

If not - please consider implementing it. It would be an extremely useful feature making Atilla stand out from other Ghost themes.

**Comment by zutrinken** [comment]
I agree, but giving it some investigation it's not that simple. I thought about global classes for `color`, `border-color`, and `background-color`. That get's us halfway. But it wouldn't cover content elements and odd cases like pseudo elements. So the best way is still changing the color variable and rebuild it one time.

**Comment by vn78dev** [comment]
Doesn't _colors.scss cover all the colors used in the theme? There are only 9 of them, if not counting for social items. I guess a typical Ghost user has no idea what does "rebuild" even mean.

**Comment by zutrinken** [comment]
That's true, but you can't change the colors in `_colors.scss` without recompiling. But I just stumbled upon [CSS variables](https://caniuse.com/#feat=css-variables). Maybe it's possible to use this.

**Comment by vn78dev** [comment]
Indeed. This is how I customised Google's material design components, for example. https://github.com/material-components/

**Comment by zutrinken** [comment]
@vn78dev Done. It's on Master. Instructions are in readme. Have fun!

**Comment by vn78dev** [comment]
@zutrinken Works like a charm. .. And you did custom fonts too! 👏
