### ISSUE TITLE
Hyvor Talk  Comments Support

### ISSUE THREAD

**Issue by jameswill377** [zutrinken/attila#129]
Please add support for Hyvor as an alternative to Disqus

Details here: https://talk.hyvor.com/

The instruction from Hyvor states that its a simple pasting of a code in the post.hbs file where it says:  If you want to add embed comments, this is a good place to do it!"

I cannot find that section in the post.hbs file. Can anyone assist?

thank you. 
<img width="910" alt="Screen Shot 2020-07-23 at 5 16 10 pm" src="https://user-images.githubusercontent.com/22332233/88260705-43413200-cd08-11ea-86f2-edd6c7fcd56f.png">

**Comment by zutrinken** [comment]
Just use the `.post-comments` section [here](https://github.com/zutrinken/attila/blob/master/post.hbs#L83-L86) and don't forget to disable the Disqus JS [here](https://github.com/zutrinken/attila/blob/master/post.hbs#L177-L193). Hope that takes you further.
