### ISSUE TITLE
Burger menu not opening on specific page

### ISSUE THREAD

**Issue by sp4rc** [zutrinken/attila#135]
I have two additional pages which are "Contact" and "About me". This pages are listed under `Settings > Design > Navigation`. They can be reached and perfectly browsed by using the navigation at width of e.g. 1280px. 

However when the mobile menu kicks in (e.g at a width of 600px) I can't open the menu anymore, after navigating to "Contact". If I browse from "Home" to "About me" I am still able to open the burger menu, but not on my "Contact" page. You can find my blog [here](https://azureblue.cadabra.blog/)

What am I doing wrong here? Any ideas? 

P.S: I am on the latest commit.

**Comment by zutrinken** [comment]
Your inserted html seams buggy. My guess is, there's a missing closing tag for e.g. `</style>` or similar, that cut's off the rest of the template where the scripts is located. That would also explain why the footer etc. is missing.

**Comment by sp4rc** [comment]
Stupid me. Your guess about the missing closing tag hit the nail on the head. Sorry for the noise...

**Comment by zutrinken** [comment]
No problem. If you're happy with theme and support I kindly ask you to consider sponsoring this project. Keeps me working on it 😎
