### ISSUE TITLE
Using prism.js for code highlighting

### ISSUE THREAD

**Issue by obitech** [zutrinken/attila#14]
Hey Peter,

first let me thank you providing such an amazing theme for free! Now, I'm just getting started with Ghost and I'd like to use prism.css and prism.js files for code blocks and inline code, how would I go about that with the Attila theme? 

Thanks!

**Comment by ddierickx** [comment]
I don't think this is specific to attila, I just followed the explanation here: 

https://grzegorowski.com/adding-code-highlighting-to-ghost-blog/ 

and that appears to work fine.

I did have some issues with line numbers which weren't properly aligned, I added some custom css to fix that:

``<style>
    .line  {
        line-height: 1.5em !important;
    }
</style>
``
