### ISSUE TITLE
Share via Reddit, and read progress indicator color

### ISSUE THREAD

**Issue by VoidMonk** [zutrinken/attila#142]
Awesome theme!

One request: please add a share icon for Reddit on the post page.

Also, I feel that if the read progress indicator color is set to `--color-primary-active` instead of `--color-primary` then it will be more distinctive. Right now, it just mixes with any links (color-primary) on the page.

Thank you.

**Comment by zutrinken** [comment]
I try to keep the sharing as minimal as possible. Rather thinking about removing it completely to be honest. You have to add reddit yourself. The progress I think looks okay.
