### ISSUE TITLE
Setting global text color

### ISSUE THREAD

**Issue by VoidMonk** [zutrinken/attila#144]
It will be good to have a global swatch setting for text color applied everywhere, like:

```
<style>
  :root {
    --color-text: #333;
  }
</style>
```

Or maybe use the `body` color.

**Comment by zutrinken** [comment]
All colors are now handled by CSS vars instead of SASS. See more [here](https://github.com/zutrinken/attila/blob/master/src/sass/_colors.scss). Should be quite easy now.
