### ISSUE TITLE
Post title gets cut off in mobile

### ISSUE THREAD

**Issue by richardjlo** [zutrinken/attila#147]
Long words like "recommendations" get cut off on mobile. Not sure if there is a workaround / solution for this. 

![image](https://user-images.githubusercontent.com/341208/92412368-86822380-f143-11ea-84ee-7bda159a38c6.png)

**Comment by filipolszewski** [comment]
Hi @richardjlo , my current workaround solution is to add this entry to your Site Header in Code Injection tab:

.post-title {
	overflow-wrap: break-word;
}

It's just good to know that in case of any changes in the template, this might stop working, e.g. if the CSS class name will change.

**Comment by richardjlo** [comment]
Hey @filipolszewski, thanks for this! I'm all set :)

**Comment by zutrinken** [comment]
@filipolszewski thanks for the support and @richardjlo for the heads up. It's fixed on master by using CSS hyphens instead of breaking words.
