### ISSUE TITLE
Turn off dark/light mode

### ISSUE THREAD

**Issue by marcogovoni** [zutrinken/attila#148]
Is it possible to use a fixed background color so to make it "static"? I want that background's color will not change in relation to user's preference on dark/light mode.

**Comment by koznov** [comment]
I think it will be great to have a switch button on the upper side of the site to choose dark or light mode of the theme.

**Comment by marcogovoni** [comment]
Yes, but I need to force users to view my blog ALWAYS with the dark mode scheme colors: how can I do this?

**Comment by marcogovoni** [comment]
Anyone can help me? Thanks

**Comment by zutrinken** [comment]
@marcogovoni You have to edit the `src/sass/style.scss`. Look for every `@media (prefers-color-scheme: dark) {...}` and move the content out of the brackets. After that you recompile the CSS with Grunt, as the [readme](https://github.com/zutrinken/attila#%EF%B8%8F-development) says.

**Comment by marcogovoni** [comment]
Thanks!
