### ISSUE TITLE
downtime over https://attila.zutrinken.com

### ISSUE THREAD

**Issue by pascalandy** [zutrinken/attila#155]
![Screen Shot 2021-01-13 at 1 03 43 PM](https://user-images.githubusercontent.com/6694151/104491170-de241600-559f-11eb-81e1-26d231e958ae.jpg)

Let me know if I can help. I'll be glad to host your demo for free as you give so much for the community. We could also set a github actions so that every commits are uploaded to the demo site.

Cheers!

**Comment by zutrinken** [comment]
@pascalandy thank you! But actually it just moved to https://attila.peteramende.de

Where did you find the old link?

**Comment by tyleryzhu** [comment]
At least for me, the link provided on https://ghost.org/marketplace/ still links to the website above that @pascalandy discovered, which I came across as well.

**Comment by pascalandy** [comment]
Lol , yeah it's from https://ghost.org/marketplace/

**Comment by zutrinken** [comment]
Ah good catch. Thanks for the heads up guys. I'll let them know.
