### ISSUE TITLE
Search and tags at the footer

### ISSUE THREAD

**Issue by jalogisch** [zutrinken/attila#158]
He

I have upgraded to the latest release and suddenly have the search and tags at the end of the page:

![image](https://user-images.githubusercontent.com/404238/108530958-6ea7f180-72d6-11eb-8eb7-2ede56b5ecbf.png)

When I switch back to 2.0.2 I'm coming from that is not a problem at all. How can I help to debug?

**Comment by jalogisch** [comment]
I just checked that happens from a change between 2.3.1 and 2.4.0. That means one of the changes from:

https://github.com/zutrinken/attila/compare/2.3.1...2.4.0

is actually made that looking strange for me at jalogisch.de - for references. Maybe you are able to help?

**Comment by jalogisch** [comment]
I guess it is the search replacement that breaks the design for me - not sure if that is because of my personal ad/tracker blocking.

**Comment by jalogisch** [comment]
actually all my failure. 

I had some caching at the nginx proxy that was hardcoded to the 2.0.2 theme so that the new assets are not loaded. 

thank you for the theme - love it!

**Comment by zutrinken** [comment]
I was just checking and wondering 🙃 ... By the way thanks a lot for your donation! Means a lot 🙌

**Comment by jalogisch** [comment]
he @zutrinken, I use your theme since version 1.something and I know that this is not made within a few minutes. Even you use that for your own I can buy you a crate of beer from time to time as thank you that you made this public usable.
