### ISSUE TITLE
Display Banner Image differently

### ISSUE THREAD

**Issue by MereCivilian** [zutrinken/attila#159]
As far as I can tell, there are two fundamental ways in displaying the banner image in a post. One is where banner image is under the title (like the Casper theme) and the other is Banner image is behind the title (like in Attila theme)

I feel if your banner image is text heavy to begin with, it will be difficult to read the title or vice versa. Please see image below:

![Compare banner image](https://user-images.githubusercontent.com/68980168/108664517-0bf96480-7527-11eb-84e1-35ffa3e21181.jpg)
(left is Casper and right is attila)

One might ask, why have text or complicated banner image to begin with. In response, I say, this image is used in social media and having text in the banner image grabs the reader's attention.

Is there anyway, I can change the Attila theme to show the image below the title?

Alternatively, if there is anyway for Ghost to use the first image in the blogpost for social media and elsewhere if the banner image is absent. 

Any insights will be appreciated.

**Comment by zutrinken** [comment]
Most simple way is to remove feature images from the template. Look for everything that says `{{#if feature_image}} … {{/if}}` in [post.hbs](https://github.com/zutrinken/attila/blob/master/post.hbs). Than place your pictures with the content and use feature image only for social media.

Alternatively you can set dedicated images for Facebook and Twitter separately. If you do that you don't have to edit the template.

**Comment by MereCivilian** [comment]
Hi @zutrinken many thanks for your response. 

I have been thinking about this a bit. There appears to be a way to not show feature image if I use an invisible tag. Let me explain, where I use the invisible tag #nofeature, I do not want the post to show the feature image. That way, for all sharing purposes, it will show the image, but it will not on the post itself. This gives me control over when I want to use feature image in the post itself.

I got this idea from: https://hooshmand.net/ghost-blog-different-hero-image-feature-image/

My request to you is how do I implement this? I know I have to do something in post.hbs file. Can you please me out here?

**Comment by zutrinken** [comment]
Interesting. It's pretty straight forward: Go to your `post.hbs` and wrap all `{{#if feature_image}} … {{/if}}` inside a `{{^has tag="#nofeature"}} … {{/has}}`. That should do the job.

But seriously, using the custom Facebook and Twitter Card settings sounds way more practical for your purpose. There you can use different pictures for cover and social media. Isn't that all you want?!

**Comment by MereCivilian** [comment]
I do not know what you mean by “wrap all”... can you please screenshot an image showing how it should look like and i will replicate that in my post.hbs file.

**Comment by zutrinken** [comment]
Untested, but I think that's it.

```
<header class="post-header {{^has tag="#nofeature"}}{{#if feature_image}} has-cover {{/if}}{{/has}}">
	<div class="inner">
		<span class="post-info">
			<span class="post-type">{{t "Article"}}</span>
			{{#if tags}}
			<span class="post-count">{{primary_tag.name}}</span>
			{{/if}}
		</span>
		<h1 class="post-title">{{{title}}}</h1>
		<div class="post-meta">
			<div class="post-meta-avatars">
				{{#foreach authors}}
					<figure class="post-meta-avatar avatar">
						{{#if profile_image}}
						<a href="{{url}}" class="author-avatar">
								<img class="author-profile-image" src="{{img_url profile_image size="xs"}}" alt="{{name}}" />
						</a>
						{{/if}}
					</figure>
				{{/foreach}}
			</div>
			<h4 class="post-meta-author">{{authors separator=", "}}</h4>
			<time datetime="{{date format='DD-MM-YYYY'}}">{{date format="DD MMM YYYY"}}</time> &bull; {{reading_time minute=(t "1 min read") minutes=(t "% min read")}}
		</div>
		{{^has tag="#nofeature"}}
		{{#if feature_image}}
		<div class="post-cover cover">
			<img
			srcset="{{img_url feature_image size="s"}} 320w,
              {{img_url feature_image size="m"}} 640w,
              {{img_url feature_image size="l"}} 960w,
              {{img_url feature_image size="xl"}} 1920w"
      src="{{img_url feature_image size="xl"}}"
			alt="{{title}}" />
		</div>
		{{/if}}
		{{/has}}
	</div>
</header>
```

**Comment by MereCivilian** [comment]
Hello Peter.

It is tested now.., and it works well. Many thanks for your help. I appreciate.

**Comment by zutrinken** [comment]
Great. Maybe you wanna buy me a [beer](https://github.com/zutrinken/attila#attila) 😉
