### ISSUE TITLE
How to force light mode?

### ISSUE THREAD

**Issue by ANONIMNIQ** [zutrinken/attila#160]
I want to use only light mode. How to stop modes based on system theme and force theme to use light mode?

**Comment by zutrinken** [comment]
Go to `src/sass/_colors.scss`, remove `.theme-dark:root {…}` and `html:not(.theme-light):root {…}`, recompile with grunt as the [readme](https://github.com/zutrinken/attila#%EF%B8%8F-development) says.

**Comment by ANONIMNIQ** [comment]
> Go to `src/sass/_colors.scss`, remove `.theme-dark:root {…}` and `html:not(.theme-light):root {…}`, recompile with grunt as the [readme](https://github.com/zutrinken/attila#%EF%B8%8F-development) says.

Thank you!
