### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by kimlehtinen** [zutrinken/attila#167]
Hi! When activating this theme, why does it have a cookie in use? I don't want any cookies when installing ghost theme :) 

![cookie](https://user-images.githubusercontent.com/17174948/109646680-22c03c80-7b61-11eb-902d-70c7190dec09.png)

**Comment by zutrinken** [comment]
Hi. It's used for switching the theme in [script.js](https://github.com/zutrinken/attila/blob/edc4c2ddd7dffc9b2b5e7d357385f92d8084636b/src/js/script.js#L270-L321) and [default.hbs](https://github.com/zutrinken/attila/blob/edc4c2ddd7dffc9b2b5e7d357385f92d8084636b/default.hbs#L21-L33).
