### ISSUE TITLE
Ghost 4.0 - Remove Sign in & Sign up Menu Links (Ghost 4.0.1)

### ISSUE THREAD

**Issue by downtrip** [zutrinken/attila#169]
Hi, Thanks for the theme, have been using it successfully with Ghost 3.x

Is there a thematic way of removing the new 'Sign in' & 'Sign up' Menu Links in Ghost 4.0.1? There is a suggestion in the forums for Casper but I can't find any equivalent in the Attila post.hbs

It doesn't seem possible from the Ghost settings which is a strange decision. Unless I'm missing something **really* obvious (very possible!)

**Comment by zutrinken** [comment]
You're right, seems like if members can't be deactivated. Go to `partials/navigation-meta.hbs` and remove [line 24-40](https://github.com/zutrinken/attila/blob/0511b79ed8b1020d2086e6d27d668970ca9dac18/partials/navigation-meta.hbs#L24-L40).

**Comment by downtrip** [comment]
That worked :) - although the relevant `{{#if...}} {{/if}}` statement was `lines 24-42` on my theme
Many thanks for the help. Can't believe this has to be done via the code

**Comment by zutrinken** [comment]
Well, there has been a theme update shortly before my last message 😉
