### ISSUE TITLE
Post titles on Homepage a little large on mobile

### ISSUE THREAD

**Issue by MereCivilian** [zutrinken/attila#176]
Hello 

Is there anyway to reduce the size of post titles on mobile? Please see image below
<img width="413" alt="Screen Shot 2021-03-28 at 8 56 57 am" src="https://user-images.githubusercontent.com/68980168/112736055-dd4a3000-8fa3-11eb-8e8b-cd00d126de2e.png">
<img width="423" alt="Screen Shot 2021-03-28 at 8 59 41 am" src="https://user-images.githubusercontent.com/68980168/112736063-f5ba4a80-8fa3-11eb-9e25-3d66b7b1bcb4.png">

**Comment by zutrinken** [comment]
I love it. Use code injection to make it smaller if needed:
````HTML
<style>
  .post-header .post-title {
    font-size: 4em;
  }
</style>
````
