### ISSUE TITLE
Tag images don’t display

### ISSUE THREAD

**Issue by mkh4lili** [zutrinken/attila#179]
Uploading a tag image displays a blank header when you display those tags via yoursite.com/tag/[tag]. 

Having no tag image displays the standard header image at the same URL. 

Shouldn’t tag images be displaying in this case, as in other themes? (If this is not desired behaviour for Attila though, please disregard.)

**Comment by zutrinken** [comment]
You're having a point and I removed the blog cover from tag and author archives. Had that on my list for too long.

But I get tag and author cover images as expected. Please double check.

**Comment by mkh4lili** [comment]
> You're having a point and I removed the blog cover from tag and author archives. Had that on my list for too long.
> 
> But I get tag and author cover images as expected. Please double check.

You are right, with 3.0 the tag cover does now work! Sorry, not sure why it didn’t appear last time.
