### ISSUE TITLE
Markdown table is not responsive.

### ISSUE THREAD

**Issue by pwnker** [zutrinken/attila#181]
When on mobile devices a table in a markdown element overflows. The table is not scrollable like codeblocks are.

Here is a screenshot of the issue:
![IMG_0191801FC3F2-1](https://user-images.githubusercontent.com/56278210/113463533-178d5480-941e-11eb-92b9-958887f3faf2.jpeg)

**Comment by Snuff-red** [comment]
> When on mobile devices a table in a markdown element overflows. The table is not scrollable like codeblocks are.
> 
> Here is a screenshot of the issue: ![IMG_0191801FC3F2-1](https://user-images.githubusercontent.com/56278210/113463533-178d5480-941e-11eb-92b9-958887f3faf2.jpeg)

I have the same question with you, did  you solve the problem?
