### ISSUE TITLE
Links in tag descriptions aren’t styled

### ISSUE THREAD

**Issue by mkh4lili** [zutrinken/attila#182]
When adding links to tag descriptions in HTML, they aren’t styled when they appear on the page header. Blue on a black background makes them unreadable.

Use case: a link to a ‘subscribe to podcast’ page in the description for /tag/podcast.

(I guess I can fix this with CSS in header injection, but it’s a bit of a workaround!)

**Comment by zutrinken** [comment]
@mkh4lili good catch. Thanks!
