### ISSUE TITLE
Image galleries no longer work

### ISSUE THREAD

**Issue by creedflan738** [zutrinken/attila#187]
This seems timed with the Ghost 4.5.0+ update. The responsive image gallery no longer works in Safari or Chrome. The image thumbnails show up, but they don't open, there's no carousel, etc. I noticed on my own website, but it's possible to verify on the demo page:

https://attila.peteramende.de/the-editor/

**Comment by creedflan738** [comment]
Is there something I can reconfigure on my end to get around this? I don't see another option in this theme to achieve similar results. Thanks.

**Comment by zutrinken** [comment]
Images were never linked. Some themes add that functionality manually. Maybe I'll add it at some point.
