### ISSUE TITLE
Links not stylized

### ISSUE THREAD

**Issue by MonaLisaOverrdrive** [zutrinken/attila#189]
Hi,

I saw that the links in the posts are working, but are not stylized with a coloured unterline or otherwise. Is this intended, or a bug? 

I attached a screenshot, where I marked the links, who are working, but you can not see that these are links in the first place. I tried the light and the dark theme, its the same on both.

<img width="803" alt="Bildschirmfoto 2021-05-30 um 15 29 36" src="https://user-images.githubusercontent.com/76841587/120106291-c15a3a80-c15c-11eb-8cca-57954fa24a02.png">
<img width="813" alt="Bildschirmfoto 2021-05-30 um 15 33 23" src="https://user-images.githubusercontent.com/76841587/120106308-c7e8b200-c15c-11eb-891e-b6a0df22b636.png">

**Comment by zutrinken** [comment]
hmm, should look like this:

<img width="817" alt="Screenshot 2021-06-10 at 21 24 55" src="https://user-images.githubusercontent.com/888679/121584956-5220f800-ca32-11eb-8693-2a2cc4505532.png">

You have a link? And Browser/OS Info?

**Comment by MonaLisaOverrdrive** [comment]
I made a tiny blog post with just three links: [Click here!](https://thewriter.co/test/)

Browser: Chrome , Version 91.0.4472.101
OS: Win 10, Build 19042.985

**Comment by zutrinken** [comment]
You're running on an older Ghost Version I think. The latest one brings a feature for setting an accent color.

**Comment by MonaLisaOverrdrive** [comment]
I updated Ghost to the newest version. It works now. Thanks.
