### ISSUE TITLE
Possibly reduce the space above the title on the main page?

### ISSUE THREAD

**Issue by 2ndMessiah** [zutrinken/attila#192]
Hi, dev

Like what's depicted above, I think it's kind of a waste of space there, how should I adjust the space above the title?

Please forgive my ignorance of front-end things...

Appreciate your hardwork. 

![image](https://user-images.githubusercontent.com/22229188/131323077-9dd0d249-9ef1-45df-914a-63dd25f9e075.png)

**Comment by zutrinken** [comment]
Go to code injection and add your custom style for `.blog-header` and `.blog-header .blog-box`. Just change the padding values. Good moment to play around with that until it fits.

```HTML
<style>
  .blog-header {
    padding-top: calc(16rem + 4vw);
  }
  .blog-header .blog-box {
    padding-bottom: calc(4rem + 2vw);
  }
</style>
```

**Comment by 2ndMessiah** [comment]
> Go to code injection and add your custom style for `.blog-header` and `.blog-header .blog-box`. Just change the padding values. Good moment to play around with that until it fits.
> 
> ```
> <style>
>   .blog-header {
>     padding-top: calc(16rem + 4vw);
>   }
>   .blog-header .blog-box {
>     padding-bottom: calc(4rem + 2vw);
>   }
> </style>
> ```

Perfect tutorial. Thx for your quick reply!
