### ISSUE TITLE
Mac OS Reader mode (Safari) displays link snippets wrong

### ISSUE THREAD

**Issue by mkh4lili** [zutrinken/attila#193]
Link snippets in Ghost display sometimes display with the header image at the linked page enlarged, and always with the whole text summary displayed. It might be better just to include the link (e.g. <http://link> on that line in Reader mode.)

Case in point: https://subvrt.org/experts/ and attached screenshots showing the same part of the page in normal and Reader modes.
<img width="837" alt="Screenshot 2021-09-01 at 00 54 32" src="https://user-images.githubusercontent.com/81428183/131581039-cd0a538b-30d8-42c2-9dbf-48dd773bd362.png">
<img width="711" alt="Screenshot 2021-09-01 at 00 54 22" src="https://user-images.githubusercontent.com/81428183/131581049-cfb6dc00-51fc-47b1-8bb2-180e50644e10.png">

**Comment by zutrinken** [comment]
Link snippets are rendered by ghost. The theme has no influence on them. Also the theme has no influence on the reader styling or output. You should rather dress it to the core platform. Nice blog btw., really like what you did with the theme!
