### ISSUE TITLE
Links not underlined

### ISSUE THREAD

**Issue by matthiasguentert** [zutrinken/attila#194]
I have just realized that links are not underlined anymore. Here is an example, the text `Spigots algorithm` really is a link, but as you can see, the styling doesn't seem right. 

![Screenshot](https://i.imgur.com/z0Xn9vx.png)

My hoster runs Ghost version 3.42.4 and the installed theme version is 3.1.0. Here is another screenshot showing chromes developer console. Any idea?

![Screenshot](https://i.imgur.com/G8sjL68.png)

If you'd like to debug the site, you can find the article [here](https://www.azureblue.io/running-a-monte-carlo-simulation-on-azure-batch/)

**Comment by matthiasguentert** [comment]
I managed to "fix" this by adding the following via code injection. Still, I don't really understand why my hack is necessary. 

```
<style>
    :root {
        --color-primary: #8dd6f9;
        --color-primary-active: #1d78c1;
    }
    
    .post-content pre .lines {
        line-height: 1.66667em;
    }

    .post-content pre code {
        line-height: 1.66667em;
    }

    .post-content a:focus, .post-content a:hover {
    	box-shadow: inset 0 -3px 0 var(--color-primary-active);
	}
    
    .post-content a {
        box-shadow: inset 0 -2px 0 var(--color-primary);
    }
</style>
```

**Comment by ditsing** [comment]
Thanks Matthias, I added your code snippet to Settings -> Code Injection -> Site header and now I have underlines for my links.

**Comment by zutrinken** [comment]
Sounds like you're running on an older ghost version. The accent color feature is needed. Similar issue [here](https://github.com/zutrinken/attila/issues/189).
