### ISSUE TITLE
Numbers in lists not visible in the dark theme

### ISSUE THREAD

**Issue by pshemk** [zutrinken/attila#195]
I use dark theme (set for the site). I've noticed that the numbers in lists end up being black:
![image](https://user-images.githubusercontent.com/8976966/135745940-6c7b91fd-a70e-4b0a-8d1a-72b42239476f.png)

The issue is with both numbered and unnumbered lists that use bullets:
![image](https://user-images.githubusercontent.com/8976966/135745976-e73f2241-b68d-4938-9250-d5edd2f268cd.png)

The issue is present in all major browser. Looking at the CSS I'm not entirely sure where the colour for the lists is set in the first instance.

**Comment by zutrinken** [comment]
You have to set a color via the ghost backend that works in light and dark mode.

**Comment by pshemk** [comment]
Thx for this. I didn't realise that this is not set via the theme.
