### ISSUE TITLE
How to change primary brand color on dark theme/light theme?

### ISSUE THREAD

**Issue by rbrtbrnschn** [zutrinken/attila#196]
I know the theme is stored in LS as `attila_theme`.

Is there another way to do this then checking each class name which uses that primary branding color and then reset that by applying styles to those elements according to the current theme?

**Comment by zutrinken** [comment]
You have to overwrite `--ghost-accent-color` with code injection:

```
<style>
:root {
  --ghost-accent-color: red;
}

.theme-dark:root {
  --ghost-accent-color: green;
}

@media (prefers-color-scheme: dark) {
  html:not(.theme-light):root {
    --ghost-accent-color: green;
  }
</style>
```

**Comment by zutrinken** [comment]
Attila now has a theme option for a dark mode accent color

<img width="357" alt="Screenshot 2022-02-03 at 12 36 24" src="https://user-images.githubusercontent.com/888679/152335650-8773e008-7d43-44fe-b349-b9c685f8987b.png">
