### ISSUE TITLE
Disqus comments are not being showed

### ISSUE THREAD

**Issue by rodrigopires** [zutrinken/attila#2]
I've already replaced the string "no-disqus" with my Disqus shortname, but comments aren't still being showed.

My Disqus accounts is properly configured, it was working with my previous Ghost theme...

Url for test: https://rodrigopires.azurewebsites.net/2015/04/21/introducao-sessions-aspnet-5/

Any idea of whats going on?

Tks!

**Comment by rodrigopires** [comment]
I've figured out that Chrome was stopping the disqus scripts to be loaded by some security reason :dizzy_face: not sure why. But now it works.

Also, I've changed the javascript to show posts on doc ready event, instead of waiting for the click in the "Show comments" button (which I've set to display none).

Cheers! :beers:

**Comment by zutrinken** [comment]
okay. nice to hear you figured it out. but nonetheless do you have any more informations about the block by chrome? do you use any security plugin? I'd like know how to reproduce it, so I can try to fix it.

**Comment by rodrigopires** [comment]
@zutrinken I guess I was using https, that was causing the problem. Shame on me :see_no_evil:
