### ISSUE TITLE
code blocks with 'text' tag don't format properly

### ISSUE THREAD

**Issue by ericseppanen** [zutrinken/attila#20]
If I want a block of preformatted text to skip syntax highlighting, this works... almost:

<pre>
```text
This is a block of text.
Syntax highlighting is
disabled.
```
</pre>

The "text" tag after the 3 backticks forces the syntax highlighting to stop, but all lines (except the first) shift to the left, overlapping the line numbers.  "nohighlight" does the same.

**Comment by zutrinken** [comment]
Thanks for report! Wasn't aware of that feature. Will fix that soon.
