### ISSUE TITLE
Search error

### ISSUE THREAD

**Issue by rdumi7ru** [zutrinken/attila#200]
Hi,

I followed the steps to enable search, and when I search for something I get this error:
`Uncaught TypeError: r is undefined`
From what I saw in the console it is referring to this:
`{var t=r.search(e.target.value,{expand:!0})`

Anyone had this issue before?

Thanks

**Comment by zutrinken** [comment]
Hey, finally had a moment to have a look. I pushed some updates and make it work with the description in the readme. But there's still a problem with fetching the excerpt. Couldn't fix that one and am waiting for a [fix in another theme](https://github.com/TryGhost/Ease/issues/22).
