### ISSUE TITLE
Can I help with french translation?

### ISSUE THREAD

**Issue by alsyia** [zutrinken/attila#204]
Hello,

I've recently began using Ghost, and I like this theme a lot. I noticed the FR translation is marked as incomplete. French is my mother tongue and the language I plan to write in, how could I help with this? 😄 

Thanks!

**Comment by zutrinken** [comment]
Hey, nice to hear and happy for your help. There are a few strings missing. Compare the [EN](https://github.com/zutrinken/attila/blob/master/locales/en.json) and [FR](https://github.com/zutrinken/attila/blob/master/locales/fr.json) files. A PR would be nice, but you can also just comment the missing ones here.
