### ISSUE TITLE
How to reduce the padding/margin under h1/h2/h3 titles in posts?

### ISSUE THREAD

**Issue by rmmdebruin** [zutrinken/attila#205]
Hi,

I would like to reduce the padding/margin under h1/h2/h3 titles in post.

See the orange area in the picture below:
![image](https://user-images.githubusercontent.com/85482745/147947212-0dfeb70c-85ee-465c-a595-a9b5fcae2dbb.png)

How do I do that?

Already many thanks and best,

Reinier

**Comment by zutrinken** [comment]
Hey, go to code injection and put this into the header section:

```
.post-content h1, .post-content h2, .post-content h3, .post-content h4, .post-content h5, .post-content h6 {
    margin-bottom: 2rem;
}
```

Adjust the value `2rem` as you like. Right now it's `4rem`.

**Comment by rmmdebruin** [comment]
Ah I missed the .post-content pointer. Thanks a lot! It works, and I also start to understand the website structure better now, including how to make changes via the code injections.

Cheers, Rein

**Comment by rmmdebruin** [comment]
I have two more (quick) questions:

- How do you adjust the vertical line spacing of lines of text in posts?
- How do you adjust the padding to the right and left of the post content for the mobile version of the website (there is now quite some white space on the right and left of the screen, when reading a post, and I would like to reduce that white space) ?

I understand that you're probably very busy, but it would help me a lot.

Already thanks and best,

Rein

**Comment by zutrinken** [comment]
### line-height

```
.post-content {
  line-height: 2em;
}
```

### padding

```
@media only screen and (max-width: 640px) {
  .inner {
    padding: 0 4rem;
  }
}
```

For other adjustments I recommend getting familiar with Dev Tools in your browser and check respective elements and classes.

**Comment by rmmdebruin** [comment]
Thanks a lot!!
