### ISSUE TITLE
Desktop font weights too light?

### ISSUE THREAD

**Issue by jagtalon** [zutrinken/attila#21]
Hello! It seems that the font weights on desktop are too hard to read. (I'm on macOS) But it seems fine on mobile devices.

<img width="1082" alt="Screenshot of attila showing the font weights" src="https://user-images.githubusercontent.com/81969/40324786-9befef54-5d07-11e8-8b8d-49be0dbeea15.png">

**Comment by zutrinken** [comment]
What browser are you using? Don't have that issue on Retina or external Display.

**Comment by jagtalon** [comment]
Hi! I was on Firefox and I think it was happening on Safari too. Sorry
I’m not on my computer right now but yeah it was pretty hard to read.
It’s ok on Safari on iOS tho. :)

On Thu, May 24, 2018, at 5:57 AM, Peter Amende wrote:
> What browser are you using? Don't have that issue on Retina or
> external Display.> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].

Links:

  1. https://github.com/zutrinken/attila/issues/21#issuecomment-391658386

**Comment by jagtalon** [comment]
Just looked! It's pretty hard to read the menu and the dates on FF, Chrome, and Safari on my computer. 

![screen shot 2018-05-25 at 12 29 45 am](https://user-images.githubusercontent.com/81969/40526193-d33d9c56-5fb2-11e8-8188-cb956261e8ed.png)
<img width="1634" alt="screen shot 2018-05-25 at 12 30 00 am" src="https://user-images.githubusercontent.com/81969/40526194-d34faca2-5fb2-11e8-96a8-8bcfb672a333.png">

**Comment by jagtalon** [comment]
Font weight of 500 seems to fix this?

<img width="1680" alt="screen shot 2018-05-25 at 1 49 37 am" src="https://user-images.githubusercontent.com/81969/40528185-f4b0d88e-5fbd-11e8-8347-cb11bb0b09b4.png">

**Comment by mceachen** [comment]
@jagtalon Cardo only has weights of 400 and 700. 

If you change `$color-blue-30` in [_colors.scss](https://github.com/zutrinken/attila/blob/master/src/sass/_colors.scss) to something darker, that should help.

**Comment by zutrinken** [comment]
The [latest version](https://github.com/zutrinken/attila/releases/tag/2.0.0) has stronger colors. Should hopefully be obsolete now.

**Comment by Jookia** [comment]
I'm affected by this issue too, especially with italics. It's very difficult to read.
