### ISSUE TITLE
No spacing between elements that follow each other

### ISSUE THREAD

**Issue by mkh4lili** [zutrinken/attila#217]
No spacing appears between the a file, video, toggle content or other new Ghost element and the following element. (Although there is spacing in the editor!) There should be spacing so it looks clean.

Screenshot shows what happens when there’s a file followed by a toggle:
<img width="841" alt="Screenshot 2022-02-20 at 20 43 24" src="https://user-images.githubusercontent.com/81428183/154858782-234d1ffe-018d-4bd9-bda6-6611b9af8f39.png">
.

**Comment by zutrinken** [comment]
Hi @mkh4lili, I couldn't reproduce that with the latest ghost version.

<img width="1162" alt="Screenshot 2022-06-19 at 12 07 18" src="https://user-images.githubusercontent.com/888679/174477164-c43ec503-52b4-4ee2-a070-f6ff6a1273bd.png">

If you still have issues, please update theme and ghost and provide a live url. thx!
