### ISSUE TITLE
Huge title on mobile version

### ISSUE THREAD

**Issue by GregFdz** [zutrinken/attila#218]
Hi
While using Attila, I noticed how big the posts' title can get on a smaller smartphone and especially on any device that uses a portrait format. This results in the title taking all the screen's space if not more. Also, the posts content are har to read, even more when it only contains text.

This is a request and a suggestion in the same time. I tried using CSS' clamp function on titles, with slightly different parameters for each the main page and post pages. For that, I clamped a vmin value between two px ones. It works quite well and adapts nicely to the screen's sizes.

Here's what I changed :

`.post-title {
    position: relative;
    z-index: 10;
    margin: 0 0 2rem;
    font-size: clamp(25px, 4vmin, 100px);
    line-height: 1.25em;
    font-weight: 700;
    text-indent: -1px;
    color: var(--color-content-lead)
}`

And then : 

`.post-header .post-title {
    margin: 0 0 4rem;
    font-size: clamp(30px, 6vmin, 220px);
    line-height: 1.25em
}`

Finally, I think that readability could be improved by using `text-align: justify`. I have to precise while suggesting this that I usually write in French. I decided to do so and I used word spacing combined with auto-hyphenation. I know that auto hyphenation is not perfect but it's still very powerful, well integrated and I think that the rare occasion when it will not function correctly are not enough to stop using it. The result is quite satifying, especially on phone ; it really improved redability and articles' overall aspect.

**Comment by zutrinken** [comment]
Hi @GregFdz, nice to hear how you make it work for you. As you pointed out, it works for you writing in French. Since every language appears differently within the theme, the idea is that everyone adjust it as they need. Even in English some people write long descriptive titles while others keep it very short and precise. There's no general solution.
