### ISSUE TITLE
Inconsolata font used in code blocks, but not imported

### ISSUE THREAD

**Issue by chintogtokh** [zutrinken/attila#22]
Only Cardo and Fira Sans are both imported in _fonts.scss, but the Inconsolata font is also used in styles.scss, and isn't loaded. Honestly think not having Inconsolata and using the default (at least on Windows & Chrome) looks better, but I've added this here just in case.

**Comment by zutrinken** [comment]
Thanks for report! That's definitely a bug. Will double check and see what works best.

**Comment by chintogtokh** [comment]
I've found just replacing fonts.scss with something like
```
@import url('https://fonts.googleapis.com/css?family=Cardo&subset=latin-ext');
@import url('https://fonts.googleapis.com/css?family=Inconsolata');
```
was the easiest fix.
