### ISSUE TITLE
Can't search Chinese now - 现在无法搜索中文，也许可以更换为fuse.js来支持中文搜索

### ISSUE THREAD

**Issue by rebron1900** [zutrinken/attila#222]
现在无法搜索中文，也许可以更换为fuse.js来支持中文搜索
---
Can't search Chinese now, maybe can be replaced for the fuse.js to support Chinese search

**Comment by zutrinken** [comment]
Do you know other ghost themes that use fuse.js as an example?

**Comment by rebron1900** [comment]
https://keima.fueko.net/ 
我以前使用的这个主题，他们使用fuse作为搜索引擎
----
I've used this theme before, and they use fuse as a search engine

**Comment by rebron1900** [comment]
plz
