### ISSUE TITLE
Consider adding support for Native Search

### ISSUE THREAD

**Issue by mfridman** [zutrinken/attila#228]
A recent Ghost 5 version (`v5.3.0`) introduced a new feature: [Native Search](https://ghost.org/changelog/search/). 

The official themes have support for Ctrl/⌘ + K keyboard shortcuts.

What are your thoughts on adding a similar search palette experience in Atilla?

**Comment by timscha** [comment]
The latest version (3.5.0) already supports the native search feature. :)

**Comment by mfridman** [comment]
Doh, sorry about that. Will upgrade to the latest version.
