### ISSUE TITLE
Portal button hides the button for color mode

### ISSUE THREAD

**Issue by timscha** [zutrinken/attila#229]
![Screen Shot 2022-07-25 at 15 10 50](https://user-images.githubusercontent.com/4650393/180785536-3a836aea-efa4-4ea3-ba64-3a8db9d061a4.png)

Is there a way to customize either the Portal Box or the Footer as easily as possible? Currently, visitors can no longer change the look of the page.

**Comment by OCram85** [comment]
This looks really annoying. It's even blocking if you're logged in:

![image](https://user-images.githubusercontent.com/13993700/191236354-b406294e-e5f9-4053-b545-df8f48081ff5.png)

![image](https://user-images.githubusercontent.com/13993700/191236453-c6a91429-593d-43ad-b42e-5770307c9a70.png)
