### ISSUE TITLE
❓ Is there a way to implement the new native comment feature in ghost 5.9+?

### ISSUE THREAD

**Issue by OCram85** [zutrinken/attila#231]
Just noticed ghost 5.9+ added a native way to comment/discuss blog posts.

Are any plans to support this feature in the theme?

![image](https://user-images.githubusercontent.com/13993700/185145371-77797e4b-039e-42d1-8fc8-54a6e7b9c9b8.png)

**Comment by frankie-mceyes** [comment]
I found out that you can easily edit one file to do that.
What I did for my blog (you can check it [here](https://mceyes.me)) was this:

1.  Go to theme folder
 - If installed directly on server, go to `$GHOST_FOLDER/themes/attila-3.5.0`
 - If installed with Docker:
    1. First do the command `docker volume inspect [container name]` and get the directory in your file system where the Docker volume saves the Ghost data
    2. Go there with `cd` command and navigate inside the `themes/attila-3.5.0` folder
2. Edit the `post.hbs` file with your favourite editor
3. Search for the string `post-comments`, that's the HTML section you need to edit
4. Remove the original `post-comment` section and create another one with another name. I changed mine into simply `comments`.
5. Simply put the `{{comments}}` handlebar inside the comment section. You can use the official [theme guide](https://ghost.org/docs/themes/helpers/comments/) from Ghost.
6. Save, exit and restart Ghost (`ghost restart` if installed directly or `docker restart [ghost container]` if installed with Docker)

This is how I edited my comment section and replaced it with the new Ghost commenting system:
```
{{!-- <section class="post-comments"> --}}
<section class="comments">
        {{comments title="Tell us what do you think!" mode="dark"}}
</section>
```

**ADDITIONALLY** you can even import the official Ghost CSS style into Attila.
1. Go to the Attila theme folder as above
2. Edit the file located at `assets/css/style.css`
3. Open in a browser the [official Casper theme](https://github.com/TryGhost/Casper), specifically the `screen.css` file. You can find it [here](https://github.com/TryGhost/Casper/blob/main/assets/css/screen.css).
4. Starting from the [line 1646](https://github.com/TryGhost/Casper/blob/main/assets/css/screen.css#L1646) select all the comments CSS elements (from line 1646 to line 1682) and append them in the attila `style.css` file, right at the end of the file will be ok.
5. Restart Ghost, so the theme will be reloaded.

If everything's ok, the new Ghost blog will have comments with the Attila theme installed 🥳

**Comment by OCram85** [comment]
Awesome detailed help! Thank you, this helps for now.
Maybe it's still worth implementing the comments section and a attila css styling into this theme directly?

**Comment by zutrinken** [comment]
I've added support for native comments. Thanks for the heads up and support all!
