### ISSUE TITLE
Missing helper: "authors" Error on Upload

### ISSUE THREAD

**Issue by derekurben** [zutrinken/attila#24]
Received the following error when trying to upload the design to my Ghost site.

<img width="507" alt="screen shot 2018-05-30 at 10 30 18 am" src="https://user-images.githubusercontent.com/9687974/40732787-b64cddaa-63f9-11e8-93b7-39c4257a928e.png">

**Comment by zutrinken** [comment]
What's your Ghost version. What's the theme version? Attila has support for authors since 1.6.0 🤔

**Comment by sepineda** [comment]
Hello @zutrinken, @derekurben . I was getting the same error, with theme versions 1.6.0 and 1.7.0 and Ghost version  1.20.3.
After updating Ghost version to 1.23.1 I'm not getting the error and can use theme version 1.7.0. :)

**Comment by jnickg** [comment]
Also seeing this issue. My server is running code based on the latest `master` of: https://github.com/cobyism/ghost-on-heroku

**Comment by louiswolfers** [comment]
Same error here, using Ghost 1.21.1 on Ubuntu 16.04, with Attila 1.7.0

**Comment by zutrinken** [comment]
Since 1.6.0 Attila supports "Authors" that came with Ghost 1.22.0 ... so if you're under 1.22 you should try 1.5.0 ... or even better: update Ghost!

**Comment by louiswolfers** [comment]
Updating Ghost fixed the issue, thank you
