### ISSUE TITLE
Disable social media share function

### ISSUE THREAD

**Issue by PlanetDyna** [zutrinken/attila#248]
Can you please tell me how to disable the social media share function?

**Comment by that-one-tom** [comment]
Hi @PlanetDyna, not sure if you're still looking for this, but to hide the sharing buttons, you can head to Settings > Advanced > Code injection and add the following code to the Site header section:

```
<style>
  .post-share {
    display: none;
  }
</style>
```

Before:

![image](https://github.com/zutrinken/attila/assets/19203795/410e7af4-a151-4e56-a653-c5712eb06db6)

After:

![image](https://github.com/zutrinken/attila/assets/19203795/1a1ae5c7-9d8c-4a80-95b3-c606d7615552)

Hope this helps :)
