### ISSUE TITLE
Responsiveness Issue

### ISSUE THREAD

**Issue by arvindravi** [zutrinken/attila#27]
Hi Peter,

Great theme you've got here! Thanks for making it. I'm having an issue with the code blocks and them not being responsive on mobile. They seem to be fine on the iPad sizes, but when its down to mobile resolution, they seem to be cut off.

Here's what I mean:

<img width="733" alt="image" src="https://user-images.githubusercontent.com/859832/42493252-eac43b5e-8439-11e8-8c83-a568f8ae7c7b.png">

This is how the Demo page looks on the same resolution:

<img width="731" alt="image" src="https://user-images.githubusercontent.com/859832/42493283-16d364cc-843a-11e8-9507-14cc8dd5edf5.png">

The demo page doesn't seem to have the issue I'm referring to.

This is how I'm using code blocks, which is pretty straightforward:

<img width="766" alt="image" src="https://user-images.githubusercontent.com/859832/42493541-0ae20046-843b-11e8-8f20-d2a15d61a34b.png">

Any thoughts on why this is happening? Thanks!

**Comment by zutrinken** [comment]
@arvindravi good catch. thanks for the report!
