### ISSUE TITLE
Feature Request:  LinkedIn and GitHub icons for Author's Bio 

### ISSUE THREAD

**Issue by hatdropper1977** [zutrinken/attila#29]
Please add LinkedIn and GitHub icons for the Author's Bio.

https://github.com/zutrinken/attila/tree/master/src/font

**Comment by zutrinken** [comment]
Hi @hatdropper1977 ... the theme should just support features the ghost backend actually provides. Please make an own version for that. The icon font is made with this tool http://fontello.com ... hope that helps.
