### ISSUE TITLE
Templates must contain valid Handlebars error

### ISSUE THREAD

**Issue by dnguneratne** [zutrinken/attila#40]
I get the following error when I try to upload this theme using Ghost's admin panel (Design -> upload theme). I'm using a Namecheap.com Ghost machine.

![image](https://user-images.githubusercontent.com/8231763/45331565-7a096700-b539-11e8-8881-866b1c3a0f23.png)

**Comment by zutrinken** [comment]
Sounds like you're running on an older Ghost version. Please make sure your Ghost version matches the required listet in the `package.json`. Or try an older theme version like [1.4.0](https://github.com/zutrinken/attila/releases/tag/1.4.0).

**Comment by dnguneratne** [comment]
1.4.0 worked, Thanks. Great theme btw!
