### ISSUE TITLE
Its throwing style.css is missing error on install in wordpress

### ISSUE THREAD

**Issue by RanjitPati** [zutrinken/attila#49]

**Comment by RanjitPati** [comment]
I just simply downloaded the Zip file. Then in wordpress I clicked on Themes then Add new and then i am successfully able to upload it. But when I am trying to install, its throwing below error:

Unpacking the package…

Installing the theme…

The package could not be installed. The theme is missing the style.css stylesheet.

Theme installation failed.

**Comment by yanzhen0610** [comment]
I thought this is for ghost only

**Comment by RanjitPati** [comment]
This is free theme from Ghost. But its throwing error at the time of install.

**Comment by zutrinken** [comment]
This theme is for Ghost, **NOT** WordPress.
