### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by chrihala** [zutrinken/attila#5]
Hi, where do I add my favicon? It's returning a 500 error by default. I'm using the theme with the Journey blog project: https://github.com/kabukky/journey

Thanks for a nice theme :+1:

**Comment by zutrinken** [comment]
Well, I'd add `<link rel="icon" type="image/png" href="{{asset "images/favicon.png"}}">` to the `default.hbs` and of course create the `assets/image/` folder with your `favicon.png`. Didn't used a favicon with ghost for now but I'd presume that this works.

**Comment by chrihala** [comment]
That works. Thanks!
