### ISSUE TITLE
Having larger paragraphs

### ISSUE THREAD

**Issue by Erwyn** [zutrinken/attila#51]
Hello there, first of all, thanks for this theme.

I was wondering if there is a possibility to widen paragraphs even if it means rebuilding the theme on my side.

For reference:
![image](https://user-images.githubusercontent.com/206743/51468506-77344380-1d6f-11e9-8862-95662519fa2e.png)

**Comment by mceachen** [comment]
Change the .inner: https://github.com/mceachen/attila/commit/fba97dc90019b21ac00d1474953f9847988ab894#diff-da725cf4823250b3f76285b47c77ac46L620

**Comment by cdorin93** [comment]
Good idea, thanks @mceachen for the push!

**Comment by deadlysyn** [comment]
First, I want to say thanks for the awesome theme...it looks amazing, and is well thought out.

Second, thanks to @mceachen for the push to DIY and easily adjust this (highly personal) preference. :-)

I've been reading Heydon Pickering's _Inclusive Design Patterns_. A section paragraph structure references Robert Bringhurst’s book _The Elements of Typographic Style_ which recommends a measure between 45 and 75 characters (based on a lot of psychology and studies about optimal line lengths for readability and accessibility).

Refer to Pickering et al pg. 51-52 if you want more detail, but in CSS this would boil down to a comfortable range somewhere around:

```css
main {  max-width: 60rem;}
```

I'm not a designer, I don't even play one on YouTube, but if this is thought to be a reasonable default I'm happy to submit a PR.

**Comment by zutrinken** [comment]
@deadlysyn I have it on the radar. I'm currently rewriting the whole theme to support some more features like darkmode. The update branch also includes better scaling on larger screens. It's still work in progress, but feel free to check it out: https://github.com/zutrinken/attila/tree/update

**Comment by cdorin93** [comment]
Awesome, thank you very much for your work! Looking forward to seeing the update :)
