### ISSUE TITLE
Show comments button always disabled

### ISSUE THREAD

**Issue by gogainda** [zutrinken/attila#57]
Tested with latest Disqus embedded code

**Comment by tankren** [comment]
Yes, Have the same issue, need to click SHOW COMMENTS every time

**Comment by zutrinken** [comment]
@gogainda do you mean the button isn't working or doesn't show up?

@tankren your case sounds like you'd like to save the state. It's by design to open it manually every time you open an article. I'd keep it that way to avoid implementing cookies.

**Comment by tankren** [comment]
@zutrinken OK!
