### ISSUE TITLE
Theme css does not load in Ghost 6.4

### ISSUE THREAD

**Issue by thisiskenfrom85** [zutrinken/attila#6]
Does this theme support Ghost 6.4?

**Comment by zutrinken** [comment]
Tested it locally with 6.4 right now and it works properly. Do you have a link so I can have a look?

**Comment by thisiskenfrom85** [comment]
Here's the site i am trying to get it working: http://thisisken.li/

**Comment by thisiskenfrom85** [comment]
Here you go: http://www.thisisken.li

**Comment by zutrinken** [comment]
Well, "_something_" does some changes.

```
<link rel="stylesheet" type="text/css" href="/assets/css/A.style.css,qv=025088c1e4.pagespeed.cf.TefeOCsHEl.css"/>
```

I guess your webserver does some caching for pagespeed afterwards and it's not the themes `style.css` that gets "changed". This is the point you have to look at since the "Attila" uses the same handlebars as ghosts default theme "Casper".

**Comment by thisiskenfrom85** [comment]
Awesome! Thanks for the info. I run Ghost using AWS on Bitnami cloud hosting. What I did was switch theme back to Casper then restarted the server. After that I change theme back to Attila and it work. I think the other theme I was using was messing things up a little.

**Comment by zutrinken** [comment]
Great! But it seems that the JS still doesn't work. At least you now know where to look at. So have fun!
