### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by tonilampela** [zutrinken/attila#65]
Now, I’m not sure if Ghost even supports this yet, but it’d be nice to have a dark mode version of Attila. 

Optimally there should be automatic detection based on media query if user’s desktop environment / browser prefers dark mode.

If this is not viable with current version of Ghost platform, then scrap this...

**Comment by zutrinken** [comment]
Ghost just has a dark mode for their backend but no theme setting option. You can detect the OS setting with media queries. Works in [FF & Safari](https://caniuse.com/#search=prefers-color-scheme) so far.

````
@media (prefers-color-scheme: light) {

}

@media (prefers-color-scheme: dark) {

}
````

It needs a lot of rewrite, but actually sounds like nice feature. Let's see what or when I can have deeper look into that.

**Comment by fesoliveira014** [comment]
Yeah, I just upgraded to Ghost 3.0 and I was really confused by the fact that Casper did not have a toggle for dark/light mode. I had to rebuild the theme enabling dark mode as the standard mode. It would be cool if Attila had this feature :)

**Comment by iMagdy** [comment]
> Yeah, I just upgraded to Ghost 3.0 and I was really confused by the fact that Casper did not have a toggle for dark/light mode. I had to rebuild the theme enabling dark mode as the standard mode. It would be cool if Attila had this feature :)

Casper 3 detects dark mode using `prefers-color-scheme`, try enabling dark mode in your OS

**Comment by fesoliveira014** [comment]
I did, but on Linux and Android it was not working, so I had to recompile the theme and force it to be in dark mode all the time.

**Comment by zutrinken** [comment]
The [latest version](https://github.com/zutrinken/attila/releases/tag/2.0.0) has a Dark Mode feature.

**Comment by joejlam** [comment]
@zutrinken I absolutely love the Attila theme. How can I disable this Dark Mode feature globally?

**Comment by zutrinken** [comment]
@joejlam You have to edit the `src/sass/style.scss` and remove all `@media (prefers-color-scheme: dark) {...}` ... afterwards you recompile the SASS with Grunt, as described in the [readme](https://github.com/zutrinken/attila#%EF%B8%8F-development).
