### ISSUE TITLE
Why are compiled assets in version control?

### ISSUE THREAD

**Issue by mhanberg** [zutrinken/attila#67]
I am wondering why are the compiled assets committed to source control?

From my own experience, this is generally a bad practice and does not really provide any value.

Thanks

**Comment by zutrinken** [comment]
It's for people without GitHub or dev experience. All they notice is a big green "Clone or download" button. Without compiled assets they would run into trouble. Therefor I don't mind having them in here. Doesn't hurt 🙂

**Comment by mhanberg** [comment]
I see, no worries!

Probably more effort than it's worth for you, but you can publish GitHub releases and attach the zipped production assets to it, without the need to keep them in source control.

Anyways, thanks for the quick reply.

https://help.github.com/en/articles/creating-releases
