### ISSUE TITLE
Not scalable to mobile

### ISSUE THREAD

**Issue by lee1409** [zutrinken/attila#68]
Hi. I was wondering why my markdown syntax is not scaled correctly to mobile version. Is anyone knows how to solve it? [Website](https://mlnotetaking.com/how-to-create-kafka-using-docker-in-5-min/) 

[Screenshot_2019-07-30-14-13-51-71](https://user-images.githubusercontent.com/7869711/62105271-82df6480-b2d4-11e9-943b-76287cf4b495.png)

**Comment by zutrinken** [comment]
I recommend using code-blocks instead of inline-code in your case.

But also I keep the issue open to add a max-width to inline-code.

**Comment by lee1409** [comment]
Okay. 👍
