### ISSUE TITLE
Bookmark card - theme update?

### ISSUE THREAD

**Issue by cdorin93** [zutrinken/attila#72]
For Ghost > 2.30: 
⚠️ **Note: Themes will require [updates](https://ghost.org/docs/api/v2/handlebars-themes/editor/#bookmark-card) to be compatible with the new bookmark card!**

Changelog: https://ghost.org/docs/api/v2/handlebars-themes/editor/#bookmark-card

**Comment by zutrinken** [comment]
Thanks for the hint!
