### ISSUE TITLE
Members support

### ISSUE THREAD

**Issue by zutrinken** [zutrinken/attila#78]
Documentation: [ghost.org/docs/members/introduction/](https://ghost.org/docs/members/introduction/)

Development branch: [members](https://github.com/zutrinken/attila/tree/members)

**Comment by OscarMcLennan** [comment]
@zutrinken when are you hoping to add member support? Love the new direction btw

**Comment by maurobanze** [comment]
The only thing keeping me from using this beautiful theme is members support, as I'm setting up a newsletter a la Substack.

**Comment by roniemartinez** [comment]
I think this should be one of the priorities.

**Comment by dorianch** [comment]
When will member support be added ? This is a beautiful theme!

**Comment by Eeems** [comment]
It's now 2021 is there an ETA on this? Or is there something you need around testing or other feedback?

**Comment by zutrinken** [comment]
All member functions are now handled out of the by ghost portal options. The theme provides sign in / up and account / upgrade buttons in the right menu. The rest is handled by ghost.

**Comment by bcye** [comment]
Thank you for finishing the feature :)
