### ISSUE TITLE
New strings need translations

### ISSUE THREAD

**Issue by zutrinken** [zutrinken/attila#83]
The latest version has [new strings](https://github.com/zutrinken/attila/blob/master/locales/en.json#L26-L29) that need to get localized:

````JSON
"Author": "Author",
"Topic": "Topic",
"Share": "Share",
"Search": "Search"
````

@robink, @fmaida, @arthurnoerve, @hao-lee, @simplyeazy, @cdorin93, @schamberg97, @cgrgrbz – I'd be super happy about a new PR or simply just a comment with the right translation.

**Comment by fmaida** [comment]
Okay. I just opened a new PR with my share of translations.

**Comment by hao-lee** [comment]
Hi, nice work!
The translation has been updated in PR [#90](https://github.com/zutrinken/attila/pull/90).

**Comment by schamberg97** [comment]
Done, check #91

**Comment by zutrinken** [comment]
@GuillaumeRZ maybe you can also help with this one?
