### ISSUE TITLE
How to modify the font used for Posts?

### ISSUE THREAD

**Issue by thebugcode** [zutrinken/attila#9]
Hi. Thanks for the theme. It would be really helpful to be able to change the font used for posts. Any ideas on how to do that?

**Comment by zutrinken** [comment]
well, at first there is the `.post` class for posts (obviously) that can be used for styling. If you take a look to the `style.scss` you can see that the styling comes from the `body` declaration or also others like `h1` or `blockquote`.

So you can modify them directly or subclass them into the `.post` class like this:
	
	.post {
		font-family: Arial, sans-serif;		

		h1, h2 {
			font-family: Avenir, sans-serif;
		}
		blockquote {
			font-family: Georgia, sans-serif;
		}
	}

Does this name your question? (Actually it’s pretty vague)

**Comment by thebugcode** [comment]
Yes, this is exactly my question. I'll try it out :) thanks
