### ISSUE TITLE
Remove social sharing icons?

### ISSUE THREAD

**Issue by kevquirk** [zutrinken/attila#95]
Is there a way to remove the social sharing icons from the bottom of blog posts from within the Admin UI?

If not, can someone point me in the direction of where I would remove that functionality from the codebase? Happy to find it myself, but someone pointing me in the right direction would be helpful.

Thanks!

**Comment by zutrinken** [comment]
You can use `Code Injection` and add:

```HTML
<style>
  .post-share {
    display: none;
  }
</style>
```

**Comment by kevquirk** [comment]
Yeah, rather than just hiding it with CSS, I wanted to remove the functionality completely. It's fine, I'll work it out.

**Comment by zutrinken** [comment]
Well, than go to your `post.hbs` and remove [line 57-71](https://github.com/zutrinken/attila/blob/master/post.hbs#L57-L71). And in the `style.scss` remove everything related to `.post-share`.

**Comment by kevquirk** [comment]
Appreciate the help, thanks.
